//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::hackathon_teams::Entity as HackathonTeams;
pub use super::hackathons::Entity as Hackathons;
pub use super::user_hackathon_roles::Entity as UserHackathonRoles;
pub use super::users::Entity as Users;
